//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("BDScrumModel", "FK__Logueo__id_Equip__300424B4", "Equipo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CADAgenda1.Equipo), "Logueo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CADAgenda1.Logueo), true)]
[assembly: EdmRelationshipAttribute("BDScrumModel", "FK__Proyecto__id_Equ__0519C6AF", "Equipo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CADAgenda1.Equipo), "Proyecto", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CADAgenda1.Proyecto), true)]
[assembly: EdmRelationshipAttribute("BDScrumModel", "FK__Tarea__id_Equipo__1920BF5C", "Equipo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CADAgenda1.Equipo), "Tarea", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CADAgenda1.Tarea), true)]
[assembly: EdmRelationshipAttribute("BDScrumModel", "FK__Historia__id_Pro__09DE7BCC", "Proyecto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CADAgenda1.Proyecto), "Historia", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CADAgenda1.Historia), true)]
[assembly: EdmRelationshipAttribute("BDScrumModel", "FK__Tarea__id_Histor__182C9B23", "Historia", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CADAgenda1.Historia), "Tarea", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CADAgenda1.Tarea), true)]
[assembly: EdmRelationshipAttribute("BDScrumModel", "FK__Sprint__id_tarea__1DE57479", "Tarea", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CADAgenda1.Tarea), "Sprint", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CADAgenda1.Sprint), true)]

#endregion

namespace CADAgenda1
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class BDScrumEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto BDScrumEntities usando la cadena de conexión encontrada en la sección 'BDScrumEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public BDScrumEntities() : base("name=BDScrumEntities", "BDScrumEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto BDScrumEntities.
        /// </summary>
        public BDScrumEntities(string connectionString) : base(connectionString, "BDScrumEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto BDScrumEntities.
        /// </summary>
        public BDScrumEntities(EntityConnection connection) : base(connection, "BDScrumEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Equipo> Equipo
        {
            get
            {
                if ((_Equipo == null))
                {
                    _Equipo = base.CreateObjectSet<Equipo>("Equipo");
                }
                return _Equipo;
            }
        }
        private ObjectSet<Equipo> _Equipo;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Historia> Historia
        {
            get
            {
                if ((_Historia == null))
                {
                    _Historia = base.CreateObjectSet<Historia>("Historia");
                }
                return _Historia;
            }
        }
        private ObjectSet<Historia> _Historia;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Logueo> Logueo
        {
            get
            {
                if ((_Logueo == null))
                {
                    _Logueo = base.CreateObjectSet<Logueo>("Logueo");
                }
                return _Logueo;
            }
        }
        private ObjectSet<Logueo> _Logueo;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Proyecto> Proyecto
        {
            get
            {
                if ((_Proyecto == null))
                {
                    _Proyecto = base.CreateObjectSet<Proyecto>("Proyecto");
                }
                return _Proyecto;
            }
        }
        private ObjectSet<Proyecto> _Proyecto;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Sprint> Sprint
        {
            get
            {
                if ((_Sprint == null))
                {
                    _Sprint = base.CreateObjectSet<Sprint>("Sprint");
                }
                return _Sprint;
            }
        }
        private ObjectSet<Sprint> _Sprint;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Tarea> Tarea
        {
            get
            {
                if ((_Tarea == null))
                {
                    _Tarea = base.CreateObjectSet<Tarea>("Tarea");
                }
                return _Tarea;
            }
        }
        private ObjectSet<Tarea> _Tarea;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Equipo. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToEquipo(Equipo equipo)
        {
            base.AddObject("Equipo", equipo);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Historia. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToHistoria(Historia historia)
        {
            base.AddObject("Historia", historia);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Logueo. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToLogueo(Logueo logueo)
        {
            base.AddObject("Logueo", logueo);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Proyecto. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToProyecto(Proyecto proyecto)
        {
            base.AddObject("Proyecto", proyecto);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Sprint. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToSprint(Sprint sprint)
        {
            base.AddObject("Sprint", sprint);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet sysdiagrams. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Tarea. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTarea(Tarea tarea)
        {
            base.AddObject("Tarea", tarea);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BDScrumModel", Name="Equipo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Equipo : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Equipo.
        /// </summary>
        /// <param name="id_Equipo">Valor inicial de la propiedad id_Equipo.</param>
        public static Equipo CreateEquipo(global::System.Int32 id_Equipo)
        {
            Equipo equipo = new Equipo();
            equipo.id_Equipo = id_Equipo;
            return equipo;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_Equipo
        {
            get
            {
                return _id_Equipo;
            }
            set
            {
                if (_id_Equipo != value)
                {
                    Onid_EquipoChanging(value);
                    ReportPropertyChanging("id_Equipo");
                    _id_Equipo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_Equipo");
                    Onid_EquipoChanged();
                }
            }
        }
        private global::System.Int32 _id_Equipo;
        partial void Onid_EquipoChanging(global::System.Int32 value);
        partial void Onid_EquipoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre_completo
        {
            get
            {
                return _nombre_completo;
            }
            set
            {
                Onnombre_completoChanging(value);
                ReportPropertyChanging("nombre_completo");
                _nombre_completo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombre_completo");
                Onnombre_completoChanged();
            }
        }
        private global::System.String _nombre_completo;
        partial void Onnombre_completoChanging(global::System.String value);
        partial void Onnombre_completoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cargo
        {
            get
            {
                return _cargo;
            }
            set
            {
                OncargoChanging(value);
                ReportPropertyChanging("cargo");
                _cargo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cargo");
                OncargoChanged();
            }
        }
        private global::System.String _cargo;
        partial void OncargoChanging(global::System.String value);
        partial void OncargoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cargo_secundario
        {
            get
            {
                return _cargo_secundario;
            }
            set
            {
                Oncargo_secundarioChanging(value);
                ReportPropertyChanging("cargo_secundario");
                _cargo_secundario = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cargo_secundario");
                Oncargo_secundarioChanged();
            }
        }
        private global::System.String _cargo_secundario;
        partial void Oncargo_secundarioChanging(global::System.String value);
        partial void Oncargo_secundarioChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BDScrumModel", "FK__Logueo__id_Equip__300424B4", "Logueo")]
        public EntityCollection<Logueo> Logueo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Logueo>("BDScrumModel.FK__Logueo__id_Equip__300424B4", "Logueo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Logueo>("BDScrumModel.FK__Logueo__id_Equip__300424B4", "Logueo", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BDScrumModel", "FK__Proyecto__id_Equ__0519C6AF", "Proyecto")]
        public EntityCollection<Proyecto> Proyecto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Proyecto>("BDScrumModel.FK__Proyecto__id_Equ__0519C6AF", "Proyecto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Proyecto>("BDScrumModel.FK__Proyecto__id_Equ__0519C6AF", "Proyecto", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BDScrumModel", "FK__Tarea__id_Equipo__1920BF5C", "Tarea")]
        public EntityCollection<Tarea> Tarea
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Tarea>("BDScrumModel.FK__Tarea__id_Equipo__1920BF5C", "Tarea");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Tarea>("BDScrumModel.FK__Tarea__id_Equipo__1920BF5C", "Tarea", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BDScrumModel", Name="Historia")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Historia : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Historia.
        /// </summary>
        /// <param name="id_Historia">Valor inicial de la propiedad id_Historia.</param>
        /// <param name="id_Proyecto">Valor inicial de la propiedad id_Proyecto.</param>
        public static Historia CreateHistoria(global::System.Int32 id_Historia, global::System.Int32 id_Proyecto)
        {
            Historia historia = new Historia();
            historia.id_Historia = id_Historia;
            historia.id_Proyecto = id_Proyecto;
            return historia;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_Historia
        {
            get
            {
                return _id_Historia;
            }
            set
            {
                if (_id_Historia != value)
                {
                    Onid_HistoriaChanging(value);
                    ReportPropertyChanging("id_Historia");
                    _id_Historia = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_Historia");
                    Onid_HistoriaChanged();
                }
            }
        }
        private global::System.Int32 _id_Historia;
        partial void Onid_HistoriaChanging(global::System.Int32 value);
        partial void Onid_HistoriaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre_Historia
        {
            get
            {
                return _nombre_Historia;
            }
            set
            {
                Onnombre_HistoriaChanging(value);
                ReportPropertyChanging("nombre_Historia");
                _nombre_Historia = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombre_Historia");
                Onnombre_HistoriaChanged();
            }
        }
        private global::System.String _nombre_Historia;
        partial void Onnombre_HistoriaChanging(global::System.String value);
        partial void Onnombre_HistoriaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> prioridad
        {
            get
            {
                return _prioridad;
            }
            set
            {
                OnprioridadChanging(value);
                ReportPropertyChanging("prioridad");
                _prioridad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("prioridad");
                OnprioridadChanged();
            }
        }
        private Nullable<global::System.Int32> _prioridad;
        partial void OnprioridadChanging(Nullable<global::System.Int32> value);
        partial void OnprioridadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> habilitar
        {
            get
            {
                return _habilitar;
            }
            set
            {
                OnhabilitarChanging(value);
                ReportPropertyChanging("habilitar");
                _habilitar = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("habilitar");
                OnhabilitarChanged();
            }
        }
        private Nullable<global::System.Boolean> _habilitar;
        partial void OnhabilitarChanging(Nullable<global::System.Boolean> value);
        partial void OnhabilitarChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_Proyecto
        {
            get
            {
                return _id_Proyecto;
            }
            set
            {
                Onid_ProyectoChanging(value);
                ReportPropertyChanging("id_Proyecto");
                _id_Proyecto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_Proyecto");
                Onid_ProyectoChanged();
            }
        }
        private global::System.Int32 _id_Proyecto;
        partial void Onid_ProyectoChanging(global::System.Int32 value);
        partial void Onid_ProyectoChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BDScrumModel", "FK__Historia__id_Pro__09DE7BCC", "Proyecto")]
        public Proyecto Proyecto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Proyecto>("BDScrumModel.FK__Historia__id_Pro__09DE7BCC", "Proyecto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Proyecto>("BDScrumModel.FK__Historia__id_Pro__09DE7BCC", "Proyecto").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Proyecto> ProyectoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Proyecto>("BDScrumModel.FK__Historia__id_Pro__09DE7BCC", "Proyecto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Proyecto>("BDScrumModel.FK__Historia__id_Pro__09DE7BCC", "Proyecto", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BDScrumModel", "FK__Tarea__id_Histor__182C9B23", "Tarea")]
        public EntityCollection<Tarea> Tarea
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Tarea>("BDScrumModel.FK__Tarea__id_Histor__182C9B23", "Tarea");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Tarea>("BDScrumModel.FK__Tarea__id_Histor__182C9B23", "Tarea", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BDScrumModel", Name="Logueo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Logueo : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Logueo.
        /// </summary>
        /// <param name="login">Valor inicial de la propiedad login.</param>
        /// <param name="id_Equipo">Valor inicial de la propiedad id_Equipo.</param>
        public static Logueo CreateLogueo(global::System.String login, global::System.Int32 id_Equipo)
        {
            Logueo logueo = new Logueo();
            logueo.login = login;
            logueo.id_Equipo = id_Equipo;
            return logueo;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String login
        {
            get
            {
                return _login;
            }
            set
            {
                if (_login != value)
                {
                    OnloginChanging(value);
                    ReportPropertyChanging("login");
                    _login = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("login");
                    OnloginChanged();
                }
            }
        }
        private global::System.String _login;
        partial void OnloginChanging(global::System.String value);
        partial void OnloginChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String contrasenia
        {
            get
            {
                return _contrasenia;
            }
            set
            {
                OncontraseniaChanging(value);
                ReportPropertyChanging("contrasenia");
                _contrasenia = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("contrasenia");
                OncontraseniaChanged();
            }
        }
        private global::System.String _contrasenia;
        partial void OncontraseniaChanging(global::System.String value);
        partial void OncontraseniaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_Equipo
        {
            get
            {
                return _id_Equipo;
            }
            set
            {
                Onid_EquipoChanging(value);
                ReportPropertyChanging("id_Equipo");
                _id_Equipo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_Equipo");
                Onid_EquipoChanged();
            }
        }
        private global::System.Int32 _id_Equipo;
        partial void Onid_EquipoChanging(global::System.Int32 value);
        partial void Onid_EquipoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Nivel_Acceso
        {
            get
            {
                return _Nivel_Acceso;
            }
            set
            {
                OnNivel_AccesoChanging(value);
                ReportPropertyChanging("Nivel_Acceso");
                _Nivel_Acceso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Nivel_Acceso");
                OnNivel_AccesoChanged();
            }
        }
        private Nullable<global::System.Int32> _Nivel_Acceso;
        partial void OnNivel_AccesoChanging(Nullable<global::System.Int32> value);
        partial void OnNivel_AccesoChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BDScrumModel", "FK__Logueo__id_Equip__300424B4", "Equipo")]
        public Equipo Equipo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Equipo>("BDScrumModel.FK__Logueo__id_Equip__300424B4", "Equipo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Equipo>("BDScrumModel.FK__Logueo__id_Equip__300424B4", "Equipo").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Equipo> EquipoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Equipo>("BDScrumModel.FK__Logueo__id_Equip__300424B4", "Equipo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Equipo>("BDScrumModel.FK__Logueo__id_Equip__300424B4", "Equipo", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BDScrumModel", Name="Proyecto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Proyecto : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Proyecto.
        /// </summary>
        /// <param name="id_Proyecto">Valor inicial de la propiedad id_Proyecto.</param>
        /// <param name="nombre_proyecto">Valor inicial de la propiedad nombre_proyecto.</param>
        /// <param name="id_Equipo">Valor inicial de la propiedad id_Equipo.</param>
        public static Proyecto CreateProyecto(global::System.Int32 id_Proyecto, global::System.String nombre_proyecto, global::System.Int32 id_Equipo)
        {
            Proyecto proyecto = new Proyecto();
            proyecto.id_Proyecto = id_Proyecto;
            proyecto.nombre_proyecto = nombre_proyecto;
            proyecto.id_Equipo = id_Equipo;
            return proyecto;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_Proyecto
        {
            get
            {
                return _id_Proyecto;
            }
            set
            {
                if (_id_Proyecto != value)
                {
                    Onid_ProyectoChanging(value);
                    ReportPropertyChanging("id_Proyecto");
                    _id_Proyecto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_Proyecto");
                    Onid_ProyectoChanged();
                }
            }
        }
        private global::System.Int32 _id_Proyecto;
        partial void Onid_ProyectoChanging(global::System.Int32 value);
        partial void Onid_ProyectoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre_proyecto
        {
            get
            {
                return _nombre_proyecto;
            }
            set
            {
                Onnombre_proyectoChanging(value);
                ReportPropertyChanging("nombre_proyecto");
                _nombre_proyecto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre_proyecto");
                Onnombre_proyectoChanged();
            }
        }
        private global::System.String _nombre_proyecto;
        partial void Onnombre_proyectoChanging(global::System.String value);
        partial void Onnombre_proyectoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha_inicio
        {
            get
            {
                return _fecha_inicio;
            }
            set
            {
                Onfecha_inicioChanging(value);
                ReportPropertyChanging("fecha_inicio");
                _fecha_inicio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_inicio");
                Onfecha_inicioChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha_inicio;
        partial void Onfecha_inicioChanging(Nullable<global::System.DateTime> value);
        partial void Onfecha_inicioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha_culminación
        {
            get
            {
                return _fecha_culminación;
            }
            set
            {
                Onfecha_culminaciónChanging(value);
                ReportPropertyChanging("fecha_culminación");
                _fecha_culminación = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_culminación");
                Onfecha_culminaciónChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha_culminación;
        partial void Onfecha_culminaciónChanging(Nullable<global::System.DateTime> value);
        partial void Onfecha_culminaciónChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String incremetno
        {
            get
            {
                return _incremetno;
            }
            set
            {
                OnincremetnoChanging(value);
                ReportPropertyChanging("incremetno");
                _incremetno = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("incremetno");
                OnincremetnoChanged();
            }
        }
        private global::System.String _incremetno;
        partial void OnincremetnoChanging(global::System.String value);
        partial void OnincremetnoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_Equipo
        {
            get
            {
                return _id_Equipo;
            }
            set
            {
                Onid_EquipoChanging(value);
                ReportPropertyChanging("id_Equipo");
                _id_Equipo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_Equipo");
                Onid_EquipoChanged();
            }
        }
        private global::System.Int32 _id_Equipo;
        partial void Onid_EquipoChanging(global::System.Int32 value);
        partial void Onid_EquipoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Objetivo
        {
            get
            {
                return _Objetivo;
            }
            set
            {
                OnObjetivoChanging(value);
                ReportPropertyChanging("Objetivo");
                _Objetivo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Objetivo");
                OnObjetivoChanged();
            }
        }
        private global::System.String _Objetivo;
        partial void OnObjetivoChanging(global::System.String value);
        partial void OnObjetivoChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BDScrumModel", "FK__Proyecto__id_Equ__0519C6AF", "Equipo")]
        public Equipo Equipo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Equipo>("BDScrumModel.FK__Proyecto__id_Equ__0519C6AF", "Equipo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Equipo>("BDScrumModel.FK__Proyecto__id_Equ__0519C6AF", "Equipo").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Equipo> EquipoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Equipo>("BDScrumModel.FK__Proyecto__id_Equ__0519C6AF", "Equipo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Equipo>("BDScrumModel.FK__Proyecto__id_Equ__0519C6AF", "Equipo", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BDScrumModel", "FK__Historia__id_Pro__09DE7BCC", "Historia")]
        public EntityCollection<Historia> Historia
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Historia>("BDScrumModel.FK__Historia__id_Pro__09DE7BCC", "Historia");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Historia>("BDScrumModel.FK__Historia__id_Pro__09DE7BCC", "Historia", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BDScrumModel", Name="Sprint")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sprint : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Sprint.
        /// </summary>
        /// <param name="id_Sprint">Valor inicial de la propiedad id_Sprint.</param>
        /// <param name="id_tarea">Valor inicial de la propiedad id_tarea.</param>
        public static Sprint CreateSprint(global::System.Int32 id_Sprint, global::System.Int16 id_tarea)
        {
            Sprint sprint = new Sprint();
            sprint.id_Sprint = id_Sprint;
            sprint.id_tarea = id_tarea;
            return sprint;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_Sprint
        {
            get
            {
                return _id_Sprint;
            }
            set
            {
                if (_id_Sprint != value)
                {
                    Onid_SprintChanging(value);
                    ReportPropertyChanging("id_Sprint");
                    _id_Sprint = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_Sprint");
                    Onid_SprintChanged();
                }
            }
        }
        private global::System.Int32 _id_Sprint;
        partial void Onid_SprintChanging(global::System.Int32 value);
        partial void Onid_SprintChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre_Sprint
        {
            get
            {
                return _Nombre_Sprint;
            }
            set
            {
                OnNombre_SprintChanging(value);
                ReportPropertyChanging("Nombre_Sprint");
                _Nombre_Sprint = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre_Sprint");
                OnNombre_SprintChanged();
            }
        }
        private global::System.String _Nombre_Sprint;
        partial void OnNombre_SprintChanging(global::System.String value);
        partial void OnNombre_SprintChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha_Inicio
        {
            get
            {
                return _fecha_Inicio;
            }
            set
            {
                Onfecha_InicioChanging(value);
                ReportPropertyChanging("fecha_Inicio");
                _fecha_Inicio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_Inicio");
                Onfecha_InicioChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha_Inicio;
        partial void Onfecha_InicioChanging(Nullable<global::System.DateTime> value);
        partial void Onfecha_InicioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Dias
        {
            get
            {
                return _Dias;
            }
            set
            {
                OnDiasChanging(value);
                ReportPropertyChanging("Dias");
                _Dias = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Dias");
                OnDiasChanged();
            }
        }
        private Nullable<global::System.Int32> _Dias;
        partial void OnDiasChanging(Nullable<global::System.Int32> value);
        partial void OnDiasChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Jornadas
        {
            get
            {
                return _Jornadas;
            }
            set
            {
                OnJornadasChanging(value);
                ReportPropertyChanging("Jornadas");
                _Jornadas = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Jornadas");
                OnJornadasChanged();
            }
        }
        private Nullable<global::System.Int32> _Jornadas;
        partial void OnJornadasChanging(Nullable<global::System.Int32> value);
        partial void OnJornadasChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Objetivo_Sprint
        {
            get
            {
                return _Objetivo_Sprint;
            }
            set
            {
                OnObjetivo_SprintChanging(value);
                ReportPropertyChanging("Objetivo_Sprint");
                _Objetivo_Sprint = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Objetivo_Sprint");
                OnObjetivo_SprintChanged();
            }
        }
        private global::System.String _Objetivo_Sprint;
        partial void OnObjetivo_SprintChanging(global::System.String value);
        partial void OnObjetivo_SprintChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 id_tarea
        {
            get
            {
                return _id_tarea;
            }
            set
            {
                Onid_tareaChanging(value);
                ReportPropertyChanging("id_tarea");
                _id_tarea = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_tarea");
                Onid_tareaChanged();
            }
        }
        private global::System.Int16 _id_tarea;
        partial void Onid_tareaChanging(global::System.Int16 value);
        partial void Onid_tareaChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BDScrumModel", "FK__Sprint__id_tarea__1DE57479", "Tarea")]
        public Tarea Tarea
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tarea>("BDScrumModel.FK__Sprint__id_tarea__1DE57479", "Tarea").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tarea>("BDScrumModel.FK__Sprint__id_tarea__1DE57479", "Tarea").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Tarea> TareaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tarea>("BDScrumModel.FK__Sprint__id_tarea__1DE57479", "Tarea");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Tarea>("BDScrumModel.FK__Sprint__id_tarea__1DE57479", "Tarea", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BDScrumModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto sysdiagrams.
        /// </summary>
        /// <param name="name">Valor inicial de la propiedad name.</param>
        /// <param name="principal_id">Valor inicial de la propiedad principal_id.</param>
        /// <param name="diagram_id">Valor inicial de la propiedad diagram_id.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BDScrumModel", Name="Tarea")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tarea : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Tarea.
        /// </summary>
        /// <param name="id_tarea">Valor inicial de la propiedad id_tarea.</param>
        /// <param name="nombre_Tarea">Valor inicial de la propiedad nombre_Tarea.</param>
        /// <param name="tipo">Valor inicial de la propiedad tipo.</param>
        /// <param name="estado">Valor inicial de la propiedad estado.</param>
        /// <param name="id_Historia">Valor inicial de la propiedad id_Historia.</param>
        /// <param name="id_Equipo">Valor inicial de la propiedad id_Equipo.</param>
        public static Tarea CreateTarea(global::System.Int16 id_tarea, global::System.String nombre_Tarea, global::System.String tipo, global::System.String estado, global::System.Int32 id_Historia, global::System.Int32 id_Equipo)
        {
            Tarea tarea = new Tarea();
            tarea.id_tarea = id_tarea;
            tarea.nombre_Tarea = nombre_Tarea;
            tarea.tipo = tipo;
            tarea.estado = estado;
            tarea.id_Historia = id_Historia;
            tarea.id_Equipo = id_Equipo;
            return tarea;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 id_tarea
        {
            get
            {
                return _id_tarea;
            }
            set
            {
                if (_id_tarea != value)
                {
                    Onid_tareaChanging(value);
                    ReportPropertyChanging("id_tarea");
                    _id_tarea = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_tarea");
                    Onid_tareaChanged();
                }
            }
        }
        private global::System.Int16 _id_tarea;
        partial void Onid_tareaChanging(global::System.Int16 value);
        partial void Onid_tareaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre_Tarea
        {
            get
            {
                return _nombre_Tarea;
            }
            set
            {
                Onnombre_TareaChanging(value);
                ReportPropertyChanging("nombre_Tarea");
                _nombre_Tarea = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre_Tarea");
                Onnombre_TareaChanged();
            }
        }
        private global::System.String _nombre_Tarea;
        partial void Onnombre_TareaChanging(global::System.String value);
        partial void Onnombre_TareaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tipo
        {
            get
            {
                return _tipo;
            }
            set
            {
                OntipoChanging(value);
                ReportPropertyChanging("tipo");
                _tipo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tipo");
                OntipoChanged();
            }
        }
        private global::System.String _tipo;
        partial void OntipoChanging(global::System.String value);
        partial void OntipoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.String _estado;
        partial void OnestadoChanging(global::System.String value);
        partial void OnestadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> horas_tarea
        {
            get
            {
                return _horas_tarea;
            }
            set
            {
                Onhoras_tareaChanging(value);
                ReportPropertyChanging("horas_tarea");
                _horas_tarea = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("horas_tarea");
                Onhoras_tareaChanged();
            }
        }
        private Nullable<global::System.DateTime> _horas_tarea;
        partial void Onhoras_tareaChanging(Nullable<global::System.DateTime> value);
        partial void Onhoras_tareaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_Historia
        {
            get
            {
                return _id_Historia;
            }
            set
            {
                Onid_HistoriaChanging(value);
                ReportPropertyChanging("id_Historia");
                _id_Historia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_Historia");
                Onid_HistoriaChanged();
            }
        }
        private global::System.Int32 _id_Historia;
        partial void Onid_HistoriaChanging(global::System.Int32 value);
        partial void Onid_HistoriaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_Equipo
        {
            get
            {
                return _id_Equipo;
            }
            set
            {
                Onid_EquipoChanging(value);
                ReportPropertyChanging("id_Equipo");
                _id_Equipo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_Equipo");
                Onid_EquipoChanged();
            }
        }
        private global::System.Int32 _id_Equipo;
        partial void Onid_EquipoChanging(global::System.Int32 value);
        partial void Onid_EquipoChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BDScrumModel", "FK__Tarea__id_Equipo__1920BF5C", "Equipo")]
        public Equipo Equipo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Equipo>("BDScrumModel.FK__Tarea__id_Equipo__1920BF5C", "Equipo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Equipo>("BDScrumModel.FK__Tarea__id_Equipo__1920BF5C", "Equipo").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Equipo> EquipoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Equipo>("BDScrumModel.FK__Tarea__id_Equipo__1920BF5C", "Equipo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Equipo>("BDScrumModel.FK__Tarea__id_Equipo__1920BF5C", "Equipo", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BDScrumModel", "FK__Tarea__id_Histor__182C9B23", "Historia")]
        public Historia Historia
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Historia>("BDScrumModel.FK__Tarea__id_Histor__182C9B23", "Historia").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Historia>("BDScrumModel.FK__Tarea__id_Histor__182C9B23", "Historia").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Historia> HistoriaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Historia>("BDScrumModel.FK__Tarea__id_Histor__182C9B23", "Historia");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Historia>("BDScrumModel.FK__Tarea__id_Histor__182C9B23", "Historia", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BDScrumModel", "FK__Sprint__id_tarea__1DE57479", "Sprint")]
        public EntityCollection<Sprint> Sprint
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Sprint>("BDScrumModel.FK__Sprint__id_tarea__1DE57479", "Sprint");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Sprint>("BDScrumModel.FK__Sprint__id_tarea__1DE57479", "Sprint", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
